In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn')
plt.style.use('dark_background')

In [24]:
class Perceptron():
    def __init__(self, X, y, numWeights, threshold, maxIters=50, loadModel=False, modelName=None):
        trainOnes = np.ones((X.shape[0], 1))
        self.X = np.hstack((X, trainOnes))
        self.y = [1 if i == 1 else -1 for i in y]
        self.numWeights = numWeights
        self.threshold = threshold
        self.maxIters = maxIters
        if loadModel:
            pass
        else:
            self.weights = np.random.normal(0, 1, numWeights + 1)
            self.iters = 0
    
    def updateWeights(self):
        for i in range(len(self.X)):
            pass


    def train(self):
        steps = 0
        while steps < self.maxIters:
            steps += 1
            self.iters += 1


In [25]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

In [26]:
p = Perceptron(X, y, 2, 0)
print(p.weights)
print(p.X)
print(p.y)

[-0.47520598 -1.30286668  0.56363703]
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[-1, -1, -1, 1]
